jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: AP01SQLIPRD001\SSIS0
      port: 1433
      database: WorkingData
      schema: dbo
      windows_login: True
      encrypt: True
      trust_cert: True